ersilia-os/ersilia

README.md

Test the forking and branching from the tutorial for new Outreachy applicants

test outreachy

---

CODE_OF_CONDUCT.md
README.md
docs/index.rst
docs/source/devel/versioning.md

Overview :
- Worked to improve the inclusivity of docs
- Made Docs beginner-friendly
- Removed Grammatical mistakes
- Removed code errors

Improved Documentation Inclusivity

---

ersilia/cli/commands/catalog.py
ersilia/hub/content/card.py
ersilia/hub/content/catalog.py

solves issue #13 
I have added the cli command :
$ersilia catalog --text  'string'
$ersilia catalog --mode 'model type'

Issue 13:Add model search functionality in the CLI

---

documentation/README_martinmwangi.md

Hello @GemmaTuron, I have added a readme file. I'll continue making improvements. Your feedback will be highly appreciated.

Ersilia outreachy

---

CONTRIBUTION.md

- Contribution guidelines are missing.
- It will be helpful for newcomers to understand how to contribute.

Created CONTRIBUTION.md

---

README.md

Have created this PR as part of improving our documentation in the Read me file

Correct grammar in the Readme file under the Road map section

---

README.md

I have "incorporated a back to top" to the README file

Add "Back to top button" to the README file

---

CONTRIBUTION.md

I added some contents in 'Contribute'.

victorabba_updated_contribution.md

---

documentation/wsl_ifeoluwafavour.md

In this file, I listed the steps to install Ersilia on a Windows system.
This pull request solves issue #26 
**Problems I faced**
- I wasn't able to use Windows Subsystem for Linux 
- I decided to download Oracle Virtualbox and Ubuntu so I would be able to use Ubuntu in my Windows system.
- It was successful and I moved on to install Git, Python and Conda for Ubuntu.
- After all the installations, I was able to create Ersilia environment and install it from Github. I prefer this method.

Created file for Windows installation of Ersilia

---

README.md

Reverts ersilia-os/ersilia#71
Hi @ps-19 
Sorry about reverting your contribution, but as specified in the issue #11 major changes to the README file need to be done by creating a separate README file in the /documentation folder, under the name README_yourname.md
Otherwise contributors will simply keep modifying each others readme files. We will revise contributions and suggest changes/merge them during the weekend.
Could you add your README file with the modifications in the relevant folder? I will leave the original one as it was so that all contributors go through the same steps
Thanks and sorry about the reversion of the contribution!

Revert "Improved Documentation Inclusivity"

---

documentation/README_Priyansh.md

As said [here](https://github.com/ersilia-os/ersilia/pull/74) tried to modify the contribution.

Created a version of README

---

documentation/README_ugochi.md

Added a  more detailed section for easy installation of Erisilia on a  windows machine,
@GemmaTuron please review, thanks.

Added Ersilia Installation section for windows machines

---

documentation/README_ElizabethJoseph

Hello @GemmaTuron @miquelduranfrigola. Below are the details of the contributions i made to the README file
1. I added the project aim to the project description
2. I added a screenshot of the schematic view of Ersilia Model Hub
3. I listed the pre-requisites for installing the model
4. I added a link to the GitHub profile of the contributors
5. I added the language used by the model
6. I added links to joining our workspace and subscribing to our mailing list.
Please do review and revert if there is need for any change. 
Thank you.

README_ElizabethJoseph

---

NEW_CONTRIBUTORS.md

guidelines for new contributors

---

README.md
documentation/README_Priyansh.md

Link of Code of conduct was actually broken.
Resolves [issue#81](https://github.com/ersilia-os/ersilia/issues/81)

Updated Broken Link

---

documentation/README_Kcfreshly.md

@GemmaTuron  @miquelduranfrigola  thank you once again for the opportunity to contribute, I know this Readme can be made a lot better. I am  open to any recommendation and 100% ready to do the revisions.
@miquelduranfrigola  hope I did it right this time?
**Project title was satisfy**
**I updated the project description**
**I updated the table of content with the new changes**
**I created a technology section that talked about the technology used by ersilia**
**I added a feature table**
**I added one or two images**
**this section was elaborated in the 'getting started' section. I also added a drop down icon so that users can find the remaining installation process for Ubuntu instead of being directed to another page**
**This was tackled by the Usage section. I used the …

Updated README.md 

---

CONTRIBUTION.md

Signed-off-by: shivani parihar <shivaniparihar1502@gmail.com>
Added 5 simple steps for new-contributors on how to contribute.

Modified CONTRIBUTION.md and added simple steps for How to contribute

---

documentation/victor_windows.md

Added a few lines to explain the Oracle virtual box.

victor_windows_updated.md

---

documentation/README_SUKRITI_SOOD.md

Created a README file as one of the Documentation tasks

added readme file

---

writing-style.md

Solves #88 
P.S. This readme isn't completed yet. It needs input from the maintainers to make the guideline more generalised.

writing style guidelines for ersilia

---

documentation/victor_windows.md

I modified the installation steps for installing Ersilia.

victor_windows.md

---

documentation/README_Kcfreshly.md

Thank you @GemmaTuron  for your recommendations. I have done the following fixes.

Updated  README.md

---

documentation/Miniconda_OR_Anaconda_DennisOnyeka.md
documentation/victor_windows.md

A pronoun (**They**) was used instead of the grammatical article (**The**)
I corrected it and the sentence is correct now.

Corrected a typo error in victor_windows.md 

---

documentation/README_Harshita.md

Issue this PR is solving  :
1. #11 
2. #49
Issue solved by adding the following components in the Readme file 
Additional Query
While creating the Readme file, I came across that we also require contributing readme additionally
I would be glad to work on it next. Can I be assigned that?
Also Do let me know what can I improve further in my PR

Write a more standard README file #11

---

documentation/README_SUKRITI_SOOD.md

Update the license name and link also.

Update  license README_SUKRITI_SOOD.md

---

documentation/README_PrachiGupta.md

I have created a README.md file. Please give your suggestions @GemmaTuron and @miquelduranfrigola.

Created a README.md file

---

tutorial/Victor_tutorial.md
tutorial/Victor_windows.md

Video tutorial on how to use the  Ersilia model hub.

Victor_tutorial.md

---

documentation/README_SUKRITI_SOOD.md

Signed-off-by: Sukriti-sood <soodsukriti1111@gmail.com>

updated Readme

---

documentation/Miniconda_OR_Anaconda_DennisOnyeka.md
documentation/victor_windows.md

I made an update to the readme file by adding system requirement needed in installing both miniconda and anaconda.
- I described in details what miniconda and anaconda is.
- I added the system requirements needed in installing either mini or anaconda distribution

Updated the MinicondaVsAnaconda readme file

---

.github/ISSUE_TEMPLATE/project-issue.yml

To streamline and standardize new issues

Issue template for new projects

---

.github/dependabot.yml

This PR will enable the Dependabot version update in ersilia-os repository.

Enabling Dependabot version updates

---

.github/ISSUE_TEMPLATE/model_request.yml
.github/workflows/approve-dispatch.yml
.github/workflows/approve-trigger.yml

This pull request creates GitHub Actions workflows to automated the "New Model Submission" flow
Related: https://github.com/ersilia-os/ersilia/issues/287

New Model Submission - Workflows

---

.github/workflows/predict-model-input.yml

This PR contains predict-model input function with input parameter.

Added predict-model input file option

---

.github/workflows/test-colab.yml
notebooks/test-collab-notebook.ipynb

run a GitHub Action that opens a Google Colab notebook,
https://github.com/ersilia-os/github-partners/issues/5
https://github.com/ersilia-os/ersilia/issues/488

Add Action to test collab

---

.github/ISSUE_TEMPLATE/model_request.yml
.github/templates/new-model.md
.github/workflows/approve-dispatch.yml

This pull request improves the current "new model submission flow" by doing the following:
- Removes the `model-id` from the issue template as we can now use the script provided by @miquelduranfrigola in https://github.com/ersilia-os/ersilia/commit/c4ba4eecc1e36ae43b1e72d970457ad0eb9629d4 to dynamically generate it for us
- Adds a new model template file (`.github/templates/new-model.md`) which is a markdown file that gets parsed by our Actions workflow and responds with the contents as a comment on our issue
- Adds the `actions/setup-python` step so we can use the aforementioned point
---
Related: https://github.com/ersilia-os/ersilia/issues/288, https://github.com/ersilia-os/ersilia/issues/287

Improve New Model Submission Flow

---

.github/workflows/quick-manual-model-test.yml

Part of: https://github.com/ersilia-os/ersilia/issues/280
Uploads logs as an artifact if the action fails
Example Runs:
Failed runs uploads artifact: 
https://github.com/ersilia-os/ersilia/actions/runs/3789468132
https://github.com/ersilia-os/ersilia/actions/runs/3789462144
Successful run doesn't upload artifact: 
https://github.com/ersilia-os/ersilia/actions/runs/3790521417

Save logs as artifact

---

AutomatedTests.ipynb

Hi,
This fixes the incorrect API call statement detailed in #524.

Fix API call statement

---

.github/scripts/update_metadata.py

This pull request adds retry logic to avoid a race condition where we try to fetch the repo contents before it is fully created due to eventual consistency

add retry logic

---

.github/workflows/predict-model.yml

Added corn job to run Ersilla prediction run every 15 minutes.

Added Corn Job to Run Ersilla Prediction Run Every 15minutes

---

.github/workflows/predict-model.yml

Added correct comment for corn job

Added correct comment for corn job

---

.github/workflows/predict-model.yml

Fix the incorrect corn schedule

Fix the incorrect corn schedule

---

ersilia/io/output.py

The following modifications are made to the output adapter to serialize .json output to .csv, to fix bugs with the eos526j and eos5qfo models.
The following modifications were made:
1. Implement a function that reads from the airtable the output shape field of the model and returns the value of the output shape field.
2. Modify the `_to_dataframe `function so that when `output shape` equals `Flexible list`, all output is written to a single column using JSONL format.

Output adapter serialize JSON to CSV

---

.github/config/exclude.txt
.github/workflows/approve-dispatch.yml
.github/workflows/approve-trigger.yml
.github/workflows/json-check.yml
.github/workflows/pr_check.yml
.github/workflows/predict-model-input.yml
.github/workflows/predict-model.yml
.github/workflows/python-publish.yml
.github/workflows/quick-manual-model-test.yml
.github/workflows/test-colab.yml
.github/workflows/test.yml
.github/workflows/write_secrets.yml
CONTRIBUTING.md

This pull request does the following:
- Updates many Actions tags / sha pins to their latest version
- Uses a new Actions based json/yml validator that runs a lot quicker and is one I recently wrote
- Adds defined Actions permissions in several workflows for better security - This _shouldn't_ break anything but if it does, let me know!
- Fixes a type in the `CONTRIBUTING.md` file with ordered lists being out of order
- Fixes a cron schedule to use a better syntax

Actions Updates

---

.github/ISSUE_TEMPLATE/project-issue.yml

This pull request contains fix for the YML syntax issue in the [project-issue.yml ](https://github.com/ersilia-os/ersilia/blob/master/.github/ISSUE_TEMPLATE/project-issue.yml) (issue template). 
Fixes: https://github.com/ersilia-os/ersilia/issues/679

Fix YML syntax error in issue template file

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This pull request sets up necessary files and configuration to use GitHub CodeSpaces with Ersilia :rocket:
---
Resolves: https://github.com/ersilia-os/ersilia/issues/698

Codespaces setup

---

.github/workflows/approve-dispatch.yml

This pull request bumps the issue-template-parser Action to `v6.0.0`.
Please let me know right away if you see any issues with the `/approve` workflow dispatch with this version upgrade! 🙇

bump issue-template-parser

---

ersilia/hub/fetch/actions/get.py

Changes are done in fetch get.py to eliminate the sudo command from dockerfile for sudo users.

Ersilia "Changes in Fetch code"

---

ersilia/hub/fetch/actions/get.py
ersilia/hub/fetch/inner_template/Dockerfile

Hi @miquelduranfrigola , 
I have had few model error hence I have been late to make contribution on this . I have made the necessary changes in the get.py file and also added some TODO comments in the case of where I didn't where to read a file or had anything else that was not clear.
The PR doesn't need be merged. I need to make the final changes.

Made the necessary changes in get.py for file creation automation.

---

.github/workflows/test.yml

@miquelduranfrigola,
Don't merge, it's just for testing. It will be deleted.

Test: setting python to 3.10.10

---

ersilia/hub/content/card.py

Import ValidationFailure if Python version<=3.7 else import ValidationError

Update card.py to correctly import from validators

---

ersilia/db/hubdata/samplers.py

The  url was only query for compound single inputs. Have added querying of pair, list, pair of list and list of list samples

Modify url to query for pair, list, pair of list and list of list samples

---

.github/workflows/python-publish.yml

Fix Poetry installation in PyPI publish workflow

---

dockerfiles/model-deploy/model/Dockerfile
dockerfiles/model-deploy/model/patch_python_path.sh

Add script to patch the path to model's python binary
Closes #1098

Patch path to model's python binary

---

.github/workflows/ersilia-base-image-to-dockerhub.yml

Use matrix strategy to control build versions in action

---

ersilia/core/tracking.py

Closes #1165 
Related to #1090

Removing the stat method from the tracking functionalites 

---

.github/templates/pull_request_template.md

A Pull request template
Add a pull request template file
**Status**
Added a pull request template file
**To do**
Let me know if there are other information to add
Closes #1126

Pull request template

---

.github/scripts/convert_airtable_to_json.py

Fixed Airtable to JSON conversion workflow script to account for paginated response from Airtable API, by iterating over the response until an offset value is present in the API response. 
Closes #1209

Fix Airtable to JSON conversion workflow to account for paginated response from Airtable API

---

ersilia/hub/content/card.py
ersilia/hub/content/catalog.py

We want the local card to be read from the model information file.
- Remove the get_service class method.
- Added model source to data being queried.
**Status**
Ersilia catalog --local --more displays the correct information for all model types.
**To do**
Related to #1072

Updated catalog local command

---

.github/scripts/update_metadata.py

Replace metadata.json with metadata.yaml in the update metadata workflow

---

dockerfiles/dockerize-ersiliapack/base/Dockerfile.conda
dockerfiles/dockerize-ersiliapack/base/Dockerfile.pip
dockerfiles/dockerize-ersiliapack/base/generate_dockerfiles.py
dockerfiles/dockerize-ersiliapack/local.md
dockerfiles/dockerize-ersiliapack/model/Dockerfile.conda
dockerfiles/dockerize-ersiliapack/model/Dockerfile.pip
ersilia/hub/fetch/lazy_fetchers/dockerhub.py
ersilia/utils/docker.py
ersilia/utils/paths.py

This PR cleans up the Dockerfiles, and related scripts; as well as adds a method to determine which packing method was used to build the model image so even if the model repository doesn't follow the new template, if it is built with Ersilia Pack (FastAPI), it follows the flows for that packing method.

Ersilia Pack Dockerization Clean up

---

ersilia/hub/content/card.py

Small PR to fix errors in parsing the new metadata files

Added support for both strings and lists in the information

---

.github/workflows/publish.yaml

This pull request updates the `publish.yaml` file to include a new feature for updating the release date field in the `CITATION.cff` file during the release process.
This task is to update the existing GitHub Actions workflow (`publish.yaml`) for the Ersilia project by automating the update of release date field in` CITATION.cff` file during the monthly release process. The existing workflow already updates the version in `CITATION.cff` and this task ensures that the release-date is also updated.
Ersilia has an automatic release trigger on the first day of each month at 3:00 AM (UTC). The workflow manages the following:
- Incrementing the version number in the pyproject.toml file. …

Update release date

---

ersilia/publish/inspect.py

This pull request updates the inspect.py script to improve model inspection by adding support for the --track flag. This change allows users to enable detailed tracking information during model inspection.
Key Changes:
Added --track flag: The script now accepts the --track flag as an optional argument, which will provide extended logging and performance tracking during the inspection process.
Enhanced logging: The logging functionality has been updated to capture and display tracking details when the --track flag is active.
Code refactoring: Minor refactoring to ensure consistent handling of input arguments and improved readability of the script.
Related to #925

Update inspect.py to include --track flag support for model inspection

---

.circleci/config.yml
ersilia/cli/commands/fetch.py
ersilia/cli/commands/run.py
ersilia/core/model.py
ersilia/hub/fetch/fetch.py
ersilia/hub/fetch/lazy_fetchers/dockerhub.py
ersilia/hub/fetch/register/register.py
ersilia/hub/pull/pull.py
ersilia/serve/standard_api.py
ersilia/utils/docker.py
ersilia/utils/identifiers/compound.py
pyproject.toml
test/test_models.py

Overall performance of the run CLI has been increased substantially by making the changes below(comparison results will be given at #1299)
1) Asynchronous and concurrent based key converter at the compound identifier
2) Caching(with dynamic custom cache size) key conversion results for smiles both from the APIs and from rdkit **(main performance boost)**
3) Adding a valid smiles checker
4) api schema and information file reader function improvement
5) reduction in the unnecessary heavy app layers
6) more
Related to #1299

Performace Improvement on the run CLI(ersilia-os#1299)

---

ersilia/hub/fetch/register/register.py

Fix control flow

---

ersilia/cli/commands/run.py
ersilia/core/model.py

1. Makes track flag work with newer models by resolving a key error in fetching model metadata
2. Cleans up double printing of outputs on the console

Miscellaneous fixes

---

dockerfiles/dockerize-ersiliapack/model/Dockerfile.conda
dockerfiles/dockerize-ersiliapack/model/Dockerfile.pip
ersilia/hub/fetch/lazy_fetchers/dockerhub.py

Copy example files from images built using ersilia pack

---

ersilia/cli/commands/fetch.py
ersilia/hub/fetch/fetch.py
test/cli/test_fetch.py

Make ersilia report docker issues better

---

.github/scripts/suggest_metadata_with_llm.py
.github/scripts/summarize_publication_with_llm.py

This is work in progress and the PR only adds some relevant scripts to be used in actions.

Model incorporation with llms

---

ersilia/serve/services.py

Related to #1511 
This PR introduces a neat way of removing temporary files specifically those found in `~/eos/sessions/session_xxxxx/_logs/tmp` (storing temporary container logs on the system storage). A new private method `_delete_temp_files` is added to the `PulledDockerImageService` class that cleans up these temporary files (and directories) before stopping and removing a model's container process. The method first lists the files and then removes them from within the container, this of course takes care of these files on the system storage as well.

Clean up temp files from model containers

---

ersilia/cli/commands/run.py
ersilia/default.py
ersilia/utils/terminal.py
test/cli/test_run.py
test/playground/commands.py
test/playground/config.yml
test/playground/noxfile.py
test/playground/utils.py

Fixing tabular output table to support all output types and DS

---

pyproject.toml

upgrade loguru

---

.github/workflows/tests_and_cleanup.yml
ersilia/setup/requirements/setuptools_req.py
test/playground/config.yml

workflow fox

---

ersilia/hub/content/base_information.py
ersilia/hub/content/card.py
ersilia/hub/content/metadata/biomedical_area.txt
ersilia/hub/content/metadata/target_organism.txt

Reverts ersilia-os/ersilia#1554
We do not want to introduce Airtable related changes in the main branch of Ersilia. All model updates will be done on a branch and then be merged when we complete the model updates

Revert "hotfix:make airtable conn work"

---

.github/workflows/tests_and_cleanup.yml
ersilia/setup/requirements/bentoml_requirement.py
ersilia/setup/requirements/setuptools_req.py
test/playground/noxfile.py
test/playground/utils.py

This PR fixes parallel job breaking issues.

Parallel session fix

---

ersilia/default.py
ersilia/hub/bundle/repo.py
ersilia/hub/delete/delete.py
ersilia/hub/fetch/actions/sniff_fastapi.py
ersilia/hub/fetch/actions/template_resolver.py
ersilia/publish/test.py
ersilia/setup/requirements/bentoml_requirement.py
ersilia/utils/exceptions_utils/fetch_exceptions.py

Packing with Ersilia Pack now resolved columns from columns file name, avoiding issues with schema resolution
Below is a Copilot-generated summary: 
This pull request includes several changes to enhance the functionality and error handling of the FastAPI model sniffing process in the Ersilia project. Key changes involve adding new exception classes, updating the `BuiltinExampleReader` class, and introducing a new `ColumnsFileReader` class.
Enhancements to FastAPI model sniffing:
* [`ersilia/hub/fetch/actions/sniff_fastapi.py`](diffhunk://#diff-f30ea9b47db6164748dc5b7c570c7db927622d4d43f59d92408759f81973b4c7L7-L16): Added new utility classes and methods to handle input and output …

Packing with Ersilia Pack now resolved columns from columns file name, avoiding issues with schema resolution

---

ersilia/default.py
ersilia/publish/test.py

Hotfix to pick the correct files in the test command
Upgrade the test command
**Status**
Hotfix, needs to be consolidated
**To do**
@Abellegese to pick this up and refactor the test command
Related to #1537

test command refactor wip 0

---

ersilia/default.py
ersilia/hub/content/base_information.py
ersilia/hub/content/metadata/biomedical_area.txt
ersilia/hub/content/metadata/deployment.txt
ersilia/hub/content/metadata/output_consistency.txt
ersilia/hub/content/metadata/pack_method.txt
ersilia/hub/content/metadata/target_organism.txt
ersilia/publish/test.py
ersilia/utils/exceptions_utils/base_information_exceptions.py

Updating the Base Information module with all the appropiate fields. Those only available in the new version of the metadata have been commented out. I'll merge this into master so everyone has all the information there and work on a separate branch eliminating the old fields. This new separate branch will not be merged until all models are updated to avoid clashes
Done
**Status**
Completed

update metadata with newest fields (commented out)

---

ersilia/publish/test/services/constants.py
ersilia/publish/test/services/io.py
ersilia/publish/test/services/runner.py
ersilia/serve/services.py

Fix for arm image endpoint issue

---

ersilia/serve/services.py
ersilia/utils/session.py
test/playground/rules.py

**Status**
**To do**
Related to #1583

refactoring codes which creates _logs from container

---

ersilia/io/output.py

parsing fix for model output

---

ersilia/io/output.py
ersilia/publish/test/services/checks.py
ersilia/utils/hdf5.py

Dimension based empty value filling in hdf5 file

---

ersilia/hub/content/base_information.py
ersilia/hub/content/catalog.py
ersilia/hub/fetch/pack/fastapi_pack/runners.py
test/collective/test_content.py
test/collective/test_models.py

Eliminate the requirement for Input Shape in the metadata. Removed the fixed version of ersilia-pack
-
**Status**
Done
**To do**
-

Eliminate input shape requeriment

---

ersilia/io/output.py

bugfix getting metadata from github

---

.github/scripts/readme_formatter.py
ersilia/cli/commands/test.py
ersilia/hub/content/base_information.py
ersilia/utils/exceptions_utils/base_information_exceptions.py
test/fields/test_airtable.py

Modified the base information and readme formatter to account for the appropriate performance fields. tried to dynamically set the property in the base information. Also ensured the tests are more consistent with current format
**Status**
Completed
Related to #1610

fix computational performance fields

---

ersilia/publish/test/services/checks.py
ersilia/publish/test/services/constants.py
ersilia/publish/test/services/io.py
ersilia/publish/test/services/runner.py
test/playground/config.yml

This pull request introduces several enhancements and refinements to the `ersilia/publish/test/services/checks.py` module, focusing on improving data validation, handling edge cases, and addressing inconsistencies in the model output checks. It also introduces new checks for column mismatches and empty column values while simplifying existing logic. Below is a summary of the most important changes grouped by theme:
* Added logic to handle metadata attributes like "Source" and "Output Consistency" to refine checks for CSV and HDF5 files, ensuring that certain validations are skipped for "Online" models or models with "Fixed" output consistency (`[[1]](diffhunk://#diff-98d38b50a9f3a365c74ab00ce330bb4b035265e9fb3a5b96a6119a6e439763a6R534-R562)`, …

Updates test command

---

ersilia/default.py
ersilia/serve/autoservice.py
ersilia/serve/services.py
ersilia/store/api.py
ersilia/store/utils.py
ersilia/utils/cache.py

Fix caching

---

ersilia/hub/content/card.py
ersilia/io/output.py
ersilia/publish/test/services/runner.py
ersilia/serve/standard_api.py

This pull request includes a minor change to the `_fetch_schema_from_github` method in the `ersilia/io/output.py` file. The change removes an unnecessary condition in the `if` statement that checks for an empty `shape` variable.
* Simplified condition in `_fetch_schema_from_github`: Removed the redundant check for `shape == 0` in the `if` statement, as it is not necessary for determining whether to return `None`. (`[ersilia/io/output.pyL437-R437](diffhunk://#diff-d045a06cd71f476160524f7bc056c76f761e3af066c00fbd63fd13d8a264171aL437-R437)`)

Model incorporation debugging

---

ersilia/cli/commands/run.py
ersilia/default.py
ersilia/serve/standard_api.py
ersilia/utils/terminal.py
test/cli/test_run.py
test/playground/config.yml

Deprecating support for string and list input types in Ersilia

---

ersilia/publish/test/services/checks.py
ersilia/publish/test/services/inspect.py
ersilia/publish/test/services/io.py
ersilia/publish/test/services/runner.py
test/collective/test_url_search.py

**Status**
**To do**
Related to #1707 #1715

bugfixes test command
