ersilia-os/ersilia

- README.md
- Fixes a tiny grammatical thing
- Links directly to the CoC page in the wiki
> Link to CoC directly

- ersilia/cli/commands/fetch.py
Solves #7 
Using the very handy GitHub API to get information about the model repo in question, then grepping the API response to simply show the `size` in KB. 
My changes to achieve this are:
```bash
import os
url = "https://github.com/ersilia-os/{0}".format(model_id)
cmd = "echo " + url + "| perl -ne 'print $1 if m!([^/]+/[^/]+?)(?:\.git)?$!' | xargs -I{} curl -s -k https://api.github.com/repos/'{}' | grep size"
echo(
"The disk storage of this model in KB is"
)
os.system(cmd) 
```
Attached herein is how the output looks currently:
> [add] Calculate disk usage of fetched model and display the same

- recipies/build.sh
- recipies/meta.yaml
Issue #9 
Hi @miquelduranfrigola . I have added the conda build recipe and made the package conda installable. I have published it on my anaconda ( https://anaconda.org/anamikayadav/ersilia ) for now. 
It can be installed using command ` $ conda install -c anamikayadav ersilia  `. When you build and publish the package from your end do let me know. I'll remove it from my channel.
> added conda recipe 

- documentation/wsl_ifeoluwafavour.md
I added a note explaining why users still need to download Conda, Python and Git for Linux while using the virtual machine.
> Updated wsl_ifeoluwafavour.md

- ersilia/cli/commands/fetch.py
Currently the cmd output of 
```
url = "https://github.com/ersilia-os/{0}.git/info/lfs".format(model_id)
cmd = "echo " + url + "| perl -ne 'print $1 if m!([^/]+/[^/]+?)(?:\.git)?$!' | xargs -I{} curl -s -k https://api.github.com/repos/'{}' | grep size"
echo(
"The disk storage of this model in KB is"
)
os.system(cmd) 
```
wasn't showing up in the terminal.
Debugged and fixed the above by:
```
print (
os.system(cmd) 
)
```
> [bfix] print the command output correctly to show the size in the CLI

- app1.py
- app2.py
- app3.py
- ersilia-app.py
- ersilia/app/contrib/app1.py
- ersilia/app/contrib/app2.py
- ersilia/app/contrib/app3.py
- ersilia/app/contrib/ersilia-app.py
I have created a simple streamlit app as suggested in issue #126
It has multi-page view that could be used to extend its functionality. 
Right now user can choose a model and perform predict and calculate operations on the given input string and display the output.
It also shows the representation of the molecular structure of the input using the rdkit python library as suggested by @GemmaTuron 
I would love to hear your feedback and work on your suggestions.
> add streamlit app ersilia-app.py

- ersilia/__init__.py
Following Issue #168
- **What was the problem?**
git-lfs not being installed caused issues while fetching big sized models like chemprop-antibiotic
- **How did I tackle the problem ?**
I've faced the problem yesterday, there is a couple of sides to it, it's if the user have a conda environment installed or he doesn't, 
the only way I found to check the conda environment was checking environment variables for variables with word "CONDA" in it, in case no conda environment was found, it will check if git-lfs is installed with python pip.
I don't have experience in writing tests for something like this, I would love to learn something like that.
> Checking if git lfs is installed

- ersilia/cli/commands/catalog.py
- ersilia/hub/content/search.py
issue #241   
I have added 2 methods to ModelSearcher Class to search using `--text` and `--mode` . To search using `--text` search_text method is added which also performs fuzzy match on the input to the data in catalog table. Fuzzy match is performed on model_id, description and slug.
search_mode method is kept same as previous search which searches the mode by which the model was trained. It doesn't perform any string matching.
Also, when no match is found user is asked to look through the catalog
> ModelSearcher updated

- .github/dependabot.yml
Configure dependabot to create 10 PRs. By default it creates only 5 PRs. We can increase this even more in the future.
Increasing the PR creation config in dependabot.yml file based on the error: https://github.com/ersilia-os/ersilia/network/updates/480983059
> Dependabot configured to create more PR

- .github/workflows/approve-dispatch.yml
Part of: https://github.com/ersilia-os/ersilia/issues/287
This updates the workflow to use a newer version of the issue-template-parser. 
This also changes how we pass the issue body and issue number to different steps.
Before the issue body's newlines were being parsed literally (so instead of `\n` being a single character, it was interpreted as a `\` character next to the letter `n`) so the parser was adding extra `\` to escape these characters. 
So,
```
```
Was being parsed as 
```
" Model Name\\n\\nTest\\n\\n"
```
which meant that `(" Model Name\\n\\nTest\\n\\n").split("\n")` returned `" Model Name\\n\\nTest\\n\\n"`. 
Ran `\approve` in two issues in Grant's actions-sandbox repo:
- Unedited issue: https://github.com/GrantBirki/actions-sandbox/issues/8#issuecomment-1319448678
- Original …
> Update workflow to handle newly created issues

- ersilia/__init__.py
Fix _version object doesn't exist on windows
> Fix _version object doesn't exist on windows

- dockerfiles/easyinstallimage/Dockerfile
- dockerfiles/easyinstallimage/dockerersilia.sh
- dockerfiles/easyinstallimage/required_files/ersilia
Added an easyinstall script in dockerfiles/easyinstallimage
This script is meant for the automation of running ersilia in docker.
It also creates an alias to ersilia in the host system.
How to use:
1. Run script dockerersilia.sh
2 The script will:
- Create a directory in ~/ersiliafiles of the host system. The directory is mounted in the Docker image in /root/eos directory.
- Try to fetch Ersilia docker image and start it.
- Add an alias to the shell rc file: alias ersilia="docker exec -it ersilia /bin/bash" - so everytime you type ersilia in the host system shell it will enter Ersilia docekr container.
> Adding a dockerfile and an easy-install script.

- ersilia/core/model.py
- ersilia/utils/exceptions_utils/throw_ersilia_exception.py
Fixed two typos in the logging statements. Replaced "if" with "is" in [model.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/core/model.py) and replaced "fill" with "will" in [throw_ersilia_exception.py](https://github.com/ersilia-os/ersilia/blob/master/ersilia/utils/exceptions_utils/throw_ersilia_exception.py).
> Fix typos in logging statements

- ersilia/utils/conda.py
It is intended to incorporate as a utility a function that allows obtaining the python path of a conda environment for future cases in which it is necessary to know this variable from the python interpreter.
> Add function that returns the python path of the conda enviroment.

- .github/workflows/approve-dispatch.yml
Pin's exact release tags and sha's for Actions stability and security. It also updates the `permissions:` block at the top of the repo to try and fix the bug where the final step fails to post a comment on the issue that triggered the Action workflow
related: https://github.com/ersilia-os/ersilia/issues/626
> Approve Updates / Fixes

- .github/dependabot.yml
Add Dependabot version update config in the dependabot.yml file to support the GitHub actions version update.
> Add support for GitHub Actions Version Update.

- .github/workflows/install.yml
- .github/workflows/pr_check.yml
- .github/workflows/predict-model-input.yml
- .github/workflows/predict-model.yml
- .github/workflows/quick-manual-model-test.yml
- .github/workflows/test-colab.yml
Hi @miquelduranfrigola,
For workflows that install ersilia, python for conda has been set to 3.10.10, and six files have been modified.
The actions that were failing;
- Deploy and test ersilia on PR: `.github/workflows/pr_check.yml`
- Install Ersilia: `.github/workflows/install.yml`
- Test Colab Notebook: `.github/workflows/test-colab.yml`
The following were not failing as they are run manually;
-  Ersilia model output prediction (Manual):  `.github/workflows/predict-model.yml`
- Ersilia model output prediction(runs every two hours but schedule is turned off):  `.github/workflows/predict-model.yml`
- Quick model test (Manual):  `.github/workflows/quick-manual-model-test.yml`
> Set Python3.10 for workflows that install ersilia

- ersilia/io/input.py
1. Use the correct flatten method for `Pair of Lists`
2. Return outputs from all flatten methods as lists for consistency with `csv.write_row` in file serialization.
> Correctly handle Pair of Lists example generation

- ersilia/db/environments/managers.py
- ersilia/publish/dockerhub.py
- ersilia/utils/terminal.py
- Added `download-miniconda.sh` to `base_files = ["Dockerfile", "docker-entrypoint.sh", "nginx.conf", "download-miniconda.sh"]`
- added support for multi-platform build
> debugged copy download-miniconda.sh and added support for multi-platform build

- .github/scripts/static_version_writer.py
- .github/workflows/python-publish.yml
- ersilia/setup/requirements/__init__.py
- pyproject.toml
> Migrate setup to poetry

- .github/workflows/python-publish.yml
Forego using Twine to publish. Use poetry directly to build and publish (which also kind of justifies the use of poetry in the first place)
> Use Poetry to publish to PyPI directly

- .github/templates/approve-workflow-failed.md
- .github/workflows/approve-dispatch.yml
This pull request leaves a comment for the user with relevant links if the `/approve` workflow fails. It didn't feel too safe to be deleting repos directly from an automated workflow run so I chose not to run those operations here. Rather, this just lets the user know a failure occurred with direct links to the orphaned repo and the workflow logs.
related: https://github.com/ersilia-os/ersilia/issues/930
> add a comment for the user on failure

- dockerfiles/model-deploy/model/Dockerfile
Some simple models do not follow the model template structure and either don't have a run.sh or a frameworks directory at all. Adding a check here to see if the file we want to modify exists. 
Refer https://github.com/ersilia-os/ersilia/issues/1098#issuecomment-2046911554
> Fix the script to patch model python binary's path

- .github/scripts/convert_airtable_to_json.py
- .github/workflows/airtable_to_json.yml
Related to this PR: [Convert Airtable models to a JSON file](https://github.com/ersilia-os/ersilia/pull/1011) In the action this issue was presented: The error "a non-empty Access Key (AKID) must be provided in the credential" and It is fixed by adding the name of the access variable key to S3 correctly.
> fix a problem with aws access key

- ersilia/cli/commands/example.py
- ersilia/default.py
- ersilia/hub/fetch/actions/get.py
- ersilia/hub/fetch/lazy_fetchers/dockerhub.py
- ersilia/io/input.py
- ersilia/publish/test.py
In this PR we add `predefined` flag to the `ersilia example` command such that if an example file (`example.csv`) exists within a model's repository, the example command uses that instead of random sampling to generate model input examples. 
Refer to issues: https://github.com/ersilia-os/ersilia/issues/1100 and https://github.com/ersilia-os/eos-template/issues/40 for why this is relevant.
> Add support for model input example.csv in the ersilia example command

- pyproject.toml
Requests which is currently set to ^2.31.0 installs 2.32.x which breaks docker_py as tracked [here](https://github.com/docker/docker-py/issues/3256).
> hotfix: pin requests to a version less than 2.31.x

- ersilia/core/tracking.py
Code refactoring to remove Pandas from the tracking functionality and implement the functionality using built-in Python libraries.
- defined `read_csv` function to read CSV files using the native CSV library.
- Replaced some other pandas data manipulation.
- Adjusted the `stats` function to calculate statistics using the statistics library.
- Adjusted the `get_file_size` function
**Status**
- The tracking functionality works with the changes. 
- Time taken is now a bit shorter.
- However there are still some inconsistencies in the outcome in comparison with the outcome generated using the tracking functionality with pandas, particularly relating to the file_size and stats functions.
**To Do**
- Refine the `check_types` function.
- Refine the …
> Code Refactor: Remove Pandas as a dependency by using the natively in built csv module instead

- pyproject.toml
Having removed pandas from the tracking functionality, it was necessary to remove it entirely from the setup (pyproject.toml) file and compare the time it takes to build the base image
- removed pandas block from pyproject.toml file
**To do**
- compare build time before removing pandas with the time after pandas has been removed
**Status**
Work in Progress
Related to #1131 #1090
> Update pyproject.toml file

- ersilia/hub/pull/pull.py
Addresses #1156 
Docker output log from failed pull on apple silicon is:
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```
current regex is:
```
r"no match.*platform.*manifest"
```
there's no 'platform' in this message so we won't match; we should remove the match on 'platform'
> fix: relax regex search of docker logs

- ersilia/cli/commands/close.py
- ersilia/cli/commands/serve.py
- ersilia/core/model.py
- ersilia/core/session.py
- ersilia/core/tracking.py
- ersilia/default.py
Resolve duplication between RunLogger in ersilia/core/session.py and RunTracker in ersilia/core/tracking.py. For example, both RunTracker and RunLogger subsample result output when the output dimensions are too many to reduce storage overhead and to not clutter the monitoring dashboard.
- Runlogger Class merged to the RunTracker classes in tracking.py,  creating a new unified class that inherits from both base classes and includes the initialization logic for both.
- Created a single __init__ method that handles the initialization requirement for tracking and logging.
- Dropped the `sample_df` method, and modified modified most of the functions in the RunTracker class. 
- Created a `track_run` function with clearer method names and simplified parameters, …
> Resolve duplication between RunLogger in ersilia/core/session.py and RunTracker in ersilia/core/tracking.py

- ersilia/cli/commands/run.py
- ersilia/cli/commands/serve.py
- ersilia/core/model.py
- ersilia/core/session.py
Remove multiple, redundant tracking flags and keep a single boolean flag with a default false value, such that by default we do not track runs for now.
Change the `track_serve` flag to `track` and ensure it tracks the session without the need to use `track_run` again.
Remove the `track_run` flag
Compare the output with the output of the former state.
**Status**
Successfully changed the multiple track flags into one (`track`)
track flag has been moved to serve
**To do**
Confirm that the metrics of several run sessions of the same model are appended to the same file
Related to #1158 #1090
> Remove multiple and redundant track flags

- ersilia/core/tracking.py
When `ersilia close` command is run, it activates the `log_file_metric` function at the end of execution. Errors and warnings encountered are tracked and logged in` current_session` file.
Also fixes the `WARNING:root:Unable to calculate metrics for log file: log file not found`.
Related to #1090
Closes  #1155
> Implement the method to log the number of errors and warnings during model run.

- ersilia/cli/commands/close.py
- ersilia/cli/commands/run.py
- ersilia/cli/commands/serve.py
- ersilia/core/model.py
- ersilia/core/session.py
- ersilia/core/tracking.py
- ersilia/utils/docker.py
- pyproject.toml
Rework code calculating memory usage - output and Docker container.
**Summary**
Ersilia model hub has different model server Implementations, each implementation handles specific deployment scenarios, such as local installation, conda environments, Docker containers, hosted services, etc. These implementations are defined in `Autoservice` class which makes use of the `service_class` objects to specify what service implementation to use for serving a model. By default, Ersilia models are fetched through Dockerhub and executed in a container. 
From this, we can split our model into two (2) groups.
- Models executed in a Docker Container.
- Models that do not utilize a Docker container.
The task here is to get three (3) key memory metrics from the underlying OS for these two …
> Rework code calculating memory usage - output and Docker container

- ersilia/core/session.py
> Fix current_service_class method to return "No model served" if ersilia process was interrupted

- ersilia/core/tracking.py
If track flag is used without specifying an output, an error is returned. This is because tracking requires a result parameter, which is the output of a run session. The error is thrown because the output being passed from run into the parameter is a generator object and not a csv file.
Wrote the generator file into a csv file, which is now read into the track function.
**Status**
Tracing now works without specifying output
**To do**
Make sure track flag works with all output formats (csv, tsv, json and h5) supported by ersilia 
Related to #1131 
Closes #1164
> Track without output bug

- ersilia/hub/content/card.py
- ersilia/hub/content/catalog.py
Related to this (comment)[https://github.com/ersilia-os/ersilia/issues/1072#issuecomment-2185852513]
Make `ersilia catalog --local --more` verbose in its output including information about how the model was fetched.
**Changes made**
- Added `get_service_class` method to the `Localcard` class in `card.py`.
- Added `service_class` method to the `Modelcard`.
- Added a series of private method to get the status, input and output type of a model in `catalog.py`.
- Modified  Local to display this new additional information.
**Status**
- Old model local catalog output  
```JSON
[
{
"Identifier": "eos4wt0",
"Slug": "morgan-fps",
"Title": "Morgan Fingerprints"
},
{
"Identifier": "eos30f3",
"Slug": "dmpnn-herg",
"Title": "Prediction of hERG Channel Blockers with Directed Message …
```
> Added the service class method to the modelcard

- ersilia/cli/commands/catalog.py
- ersilia/core/session.py
- ersilia/hub/content/catalog.py
When you try to run ersilia catalog --local but no models are available locally, instead of telling you there is no local model available, it outputs an error:
-updated the `local` method to return an empty `catalogue_table` if no models are found.
-updated the `catalogue` command to print a message when the `catalogue_table` has no data
**Status**
"No local model is available. Please fetch a model by running 'ersilia fetch ...'" is returned when you run  `ersilia catalog --local` and no local model is available 
Related to #1072
> Ersilia Catalog Bug when no models are available

- ersilia/hub/delete/delete.py
During a GitHub Actions workflow or when fetching on a system without BentoML installed, BentoML is automatically installed using the command `git clone --filter=blob:none --quiet https://github.com/ersilia-os/bentoml-ersilia.git /tmp/pip-req-build-4zsvpc12` , BentoML services are then listed and saved in a catalog, a debug method was used to output this catalog before the services apart from the latest one are deleted during fetching.
**Changes made**
- Debug statement deleted.
**Status**
Code does not appear in git action anymore.
Closes #1080
> Remove annoying debug logs

- ersilia/cli/commands/run.py
- ersilia/cli/commands/serve.py
- ersilia/core/tracking.py
The time tracking method in use does not accurately depicts the time taken in a model run
**Changes made**
- Introduce an `update_total_time` method in `tracking.py` to get an accurate measure of time across the two (2) process, minus the time spent waiting for user input(for the CLI).
- Track time in `serve.py`.
- Track time in `run.py`.
**Status**
- A time value that reflects and depicts the total time taken for our model to run.
Related to #1090
> Modified the time tracking method to accurately track time taken

- ersilia/core/model.py
- ersilia/core/tracking.py
- ersilia/utils/csvfile.py
Making tracking work when input is just a single SMILE string.
- Modified and moved `read_csv` method to `utils/csv`, and created a dictionary method to process generator output before storing to a CSV file.
- A minor fix in `model.py` to enable tracking if `standard run` was enabled.
**Status**
Tracking works with different input/output formats.
Related to #1170
> Refactor tracking to support a single SMILES string input

- ersilia/hub/fetch/actions/sniff.py
For models such as eos78ao (Mordred Descriptor), Ersilia is not able to resolve the model's datatype in its API schema to a `numeric_array` because of the presence of Null values for some of the descriptors in the model output. We know that the model outputs, in the ideal case, consist of only integer and float values, therefore the the datatype field should be set to `numeric_array`. 
**Changes**
In this PR, a private method `_get_schema_type_for_simple_run_api_case` has been implemented to ascertain the model's output type and shape using model metadata fields such as `Output Type` and `Output Shape`. This method sets the field `type` in model's API schema to `numeric_array`, if `Output Type` is set to Float and `Output Shape` is set to List in the model's metadata. This …
> Utilise model metadata to resolve model output type and shape

- ersilia/utils/docker.py
This PR fixes model fetch from Ersilia using github especially when it is in a Docker container.
**Changes made**
Moved docker client init from `SimpleDocker` init to where it is actually needed to be used (ie in the `get_container` method).
Closes #1192
> Fix bug with ersilia fetch from github inside a docker container

- ersilia/cli/commands/fetch.py
- ersilia/default.py
- ersilia/hub/content/information.py
- ersilia/hub/fetch/fetch.py
Keeping track of where a model was fetched from, whether a repository or storage location seems crucial, a model source descriptor was created to store these values.
- Created a model_source file.
- Added a  `_get_model_source` method to the information class.
- Included model source in the data response payload in the get method.
- Modified the code to also include local path.
**Status**
- The get method returns a data response payload that includes the model source, along with other attributes such as pack mode, service class, API schema, size, metadata, and card."
- Information.json file now includes model source in its data object.
- Model source is not …
> Getting model source value

- ersilia/hub/fetch/lazy_fetchers/dockerhub.py
- ersilia/hub/pull/pull.py
For models that are fetched from docker,   they have their information file being copied from the container storage to the host machine, this might lead to some incorrect data schema as the file being copied is a representation of the model environment inside the container and not the one on the host machine.
Added a modify_information method to docker functionality, to modify the content of what is being copied from docker container.
**Status**
The information file now reflects the correct service class and size for model's fetched from DockerHub.
[information.json](https://github.com/user-attachments/files/16302518/information.json)
**To do**
Include model …
> Reflecting correct values in Model information file

- ersilia/publish/test.py
- pyproject.toml
Marking Scikit Learn, and Scipy as optional because those are only required by the `ersilia test` module to make the basic ersilia install lightweight.
> Clean up dependencies related to ersilia test module

- ersilia/core/modelbase.py
- ersilia/hub/content/card.py
- ersilia/hub/content/slug.py
`ModelBase` class initialises `Slug` during its own init, which in turn inits `ModelCard` which inits `AirtableInterface` which ends up installing PyAirtable even if eventually Airtable doesn't end up getting used, so fix `ModelCard` to not init all card readers during its own init.
Additionally, call to `AirtableCard` methods via `ModelCard` within methods in `Slug` are replaced by `ModelCard.get` so it is more agnostic of whichever card eventually ends up getting used. 
Related to #1242
> Make PyAirtable optional

- ersilia/hub/content/card.py
- ersilia/hub/content/catalog.py
- ersilia/hub/content/slug.py
> Fix 'card' KeyError in ersilia catalog command

- ersilia/setup/requirements/compound.py
* replace deprecated rdkit-pypi with rdkit package
* pin rdkit version to 2023.9.1
- [ x] Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [x ] Have you written new tests for your core changes, as applicable?
- [ x] Have you successfully ran tests with your changes locally?
Related to #1304
> Bump rdkit version (#1304)

- test/test_compound_identifier.py
Added a negative test for the is_key_header method in the CompoundIdentifier class. The goal is to make ensure that any input not matching "key" or "inchikey" in any case format should return false
- Added `test_is_key_header_negative` test function in test_compound_identifier.py
- The test contains string of input header that is not "key", "inchikey"
- The list include invalid header that are similar to the valid input
**Status**
- Created the negative test for is_key_header
- Ran the test locally using pytest. Output of running the test [is_key_header.log](https://github.com/user-attachments/files/17414779/is_key_header.log) 
**To do**
Further unit test for …
> Add negative unit test for is_key_header in test_compound_identifier.py

- ersilia/core/modelbase.py
- ersilia/db/hubdata/samplers.py
- ersilia/hub/content/card.py
- ersilia/hub/content/information.py
- ersilia/hub/fetch/actions/get.py
- ersilia/hub/fetch/actions/sniff_bentoml.py
- ersilia/io/pure.py
- ersilia/publish/inspect.py
- ersilia/publish/metadata.py
- ersilia/utils/paths.py
This PR does a couple of things, but the main goal is build compatibility with Ersilia Pack's metadata storage format.
1. Reading metadata within ersilia is now agnostic of which format the metadata file follows, ie whether it is a JSON file or a YAML file (following the new template)
2. I've implemented a custom loader class for parsing the YAML file so it always loads the metadata in the data structure that is expected throughout ersilia. 
3. Parts of the code that tried to read metadata from the metadata file now use a util function, `get_metadata_from_base_dir`, found in `utils/paths` to get the metadata. This method looks for either the JSON or the YAML file and if neither is found, raises a `FileNotFoundError`.
> Make ersilia metadata file agnostic

- ersilia/cli/commands/fetch.py
- ersilia/core/modelbase.py
- ersilia/core/tracking.py
- ersilia/db/hubdata/sanitize.py
- ersilia/hub/fetch/actions/get.py
- ersilia/hub/fetch/actions/prepare.py
- ersilia/hub/fetch/actions/sniff_bentoml.py
- ersilia/hub/fetch/actions/sniff_fastapi.py
- ersilia/hub/fetch/fetch.py
- ersilia/hub/fetch/lazy_fetchers/dockerhub.py
- ersilia/hub/fetch/pack/bentoml_pack/runners.py
- ersilia/hub/fetch/pack/fastapi_pack/runners.py
- ersilia/hub/fetch/register/register.py
- ersilia/hub/fetch/register/standard_example.py
- ersilia/hub/pull/pull.py
- ersilia/io/input.py
- ersilia/publish/test.py
- ersilia/serve/services.py
- ersilia/setup/requirements/eospath.py
- ersilia/setup/requirements/git.py
- ersilia/setup/requirements/ping.py
- ersilia/utils/conda.py
- ersilia/utils/exceptions_utils/throw_ersilia_exception.py
- ersilia/utils/tracking.py
- ersilia/utils/venv.py
Logs below:
```bash
00:16:09 | DEBUG    | Activation done
00:16:09 | DEBUG    | Packing command successfully run inside eos8ub5 conda environment
00:16:09 | DEBUG    | Creating model symlink bundle > dest
00:16:09 | DEBUG    | Creating symlink from /home/dee/eos/repository/eos8ub5/20241119-9eadd098-3169-4cac-8e85-697055a510a0/model
00:16:09 | DEBUG    | Creating symlink to /home/dee/eos/dest/eos8ub5/model
00:16:09 | INFO     | Could not create symbolic link from /home/dee/eos/dest/eos8ub5/data.h5 to /home/dee/eos/isaura/lake/eos8ub5_public.h5
00:16:09 | DEBUG    | Symlinks created
00:16:09 | DEBUG    | Getting model card of eos8ub5
00:16:09 | DEBUG    | Trying to get metadata from: /home/dee/eos/dest/eos8ub5
00:16:09 | DEBUG    | Card saved at /home/dee/eos/dest/eos8ub5/card.json
00:16:09 …
```
> Make fetch fail if standardrun doesnt work

- pyproject.toml
Unnecessary dependency inclusion for something that is already in Python's site packages.
> Remove setuptools dependency

- ersilia/cli/commands/run.py
- ersilia/core/model.py
- ersilia/io/readers/file.py
- ersilia/serve/standard_api.py
- test/cli/test_run.py
The aim of this PR is to generalize standard run to work with any type of model server response and be able to serialize a CSV output file. In addition to that, other changes introduced through this PR are:
- We can now calculate the output csv header from a predefined example file, in addition to the standard csv output file
- The is_ready function from the StandardCSVRunApi class is removed, and only the is_amenable function is kept because the checks in the latter were a superset of the ones in is_ready.
- Unused code is removed
- The `run` method no longer has a try_standard parameter because standard run is the default behavior.
> Generalize Standard Run 

- ersilia/cli/commands/catalog.py
- ersilia/db/hubdata/interfaces.py
- ersilia/hub/content/card.py
- ersilia/hub/content/catalog.py
> Refactor catalog command to show local catalog by default

- ersilia/cli/commands/catalog.py
- ersilia/cli/commands/example.py
- ersilia/hub/content/catalog.py
- ersilia/io/input.py
- ersilia/utils/exceptions_utils/exceptions.py
This PR introduces more changes to make the catalog command simpler:
> Refactor Catalog command

- ersilia/core/modelbase.py
The fix includes raising an error when the model directory doesn't exist on the system.
Logs after the implemented fix:
```python
(ersilia) ☁  ersilia-project  ersilia -v fetch eos9iyc --from_dir ./eos9iyc
From dir:  ./eos9iyc
17:38:05 | DEBUG    | Repo path specified: ./eos9iyc
17:38:05 | DEBUG    | Absolute path: /home/user/ersilia-project/eos9iyc
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨
Error message:
Model directory does not exist at the provided path. Please check the path and try again.
If this error message is not helpful, open an issue at:
- https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
- hello[at]ersilia.io
If you haven't, try to run your command in verbose mode (-v in the CLI)
- You will find the console log file in: /home/user/eos/current.log
``` …
> Raise error if model directory doesn't exist

- ersilia/cli/commands/delete.py
Due to recent changes made in which data columns are stored in the [CatalogTable](https://github.com/ersilia-os/ersilia/pull/1426), it had a downstream effect on the delete functionality, wherein we first access the local catalog and read each line item in the catalog table, assuming that the first column in each row contains the model identifier. The PR removes this hard coding of the column index by first getting the correct column index and then using it to access the right field in the row.
Closes #1468
> Access the correct index to get model identifier when deleting all local models

- ersilia/cli/commands/close.py
- ersilia/cli/commands/serve.py
- ersilia/core/session.py
- ersilia/hub/delete/delete.py
- ersilia/utils/session.py
Track served models with their session info so if they are deleted while being served, we can safely remove their session data. This ensures that command such as `ersilia info`, and `ersilia example` do not pick up residual session information for models that don't even exist on the user's system.
Closes #1462
> Clean up session information for deleted models

- ersilia/core/model.py
- ersilia/hub/fetch/actions/sniff_bentoml.py
- test/test_models.py
Closes #1449 
This PR aims to make the Python API, ie the `ErsiliaModel` class work as intended, ie through a synchronous API, without the keyword `async`. To that effect, the API now looks like:
```python
(ersilia) ☁  ~  python
Python 3.10.13 (main, Aug  1 2024, 16:45:21) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ersilia import ErsiliaModel
>>> em = ErsiliaModel("molecular-weight")
>>> em.fetch()
>>> em.serve()
>>> em.run("CCCCC")
<generator object ErsiliaModel._api_runner_iter at 0x131df52a0>
>>> res = list(em.run("CCCCC"))
>>> res
[{'input': {'key': 'OFBQJSOFQDEBGM-UHFFFAOYSA-N', 'input': 'CCCCC', 'text': 'CCCCC'}, 'output': {'value': 72.151}}]
>>>
```
A model can also be fetched outside of the …
> Make python api work

- ersilia/cli/commands/example.py
- ersilia/cli/commands/run.py
- ersilia/hub/content/catalog.py
- ersilia/io/input.py
- ersilia/utils/terminal.py
Closes #1486 
The PR makes the following updates:
1. The `--random` flag is set by default now in the example command, so the example command now indeed generates random samples unless `predefined` is requested, and an example file actually exists.
2. The `--as-table` flag for the `run` command has a shorter `-t` flag now.
3. `catalog` command accepts any extension and supports both tab separated files and comma separated files, however when the file extension is not `.tsv`, it serializes the file as a CSV by default.
4. The `example` command logs to the user if it is unable to find an example file for the model and that it is generating random samples.
> Final CLI Improvements

- README.md
- ersilia/hub/fetch/fetch.py
This PR aims to fix the `Python 3.12` compatibility issue with Bentoml. Implementation to be done within the fetch at the beginning (regardless of whether it's bentoml, or fastapi), just to be safe.
Bug: The issue stems from `pkg_resources` incompatibility with `Python 3.12` due to the removal of `pkgutil.ImpImporter`. 
`Python 3.12` removed `pkgutil.ImpImporter` and also stopped pre-installing `setuptools` in` venv` environments.` setuptools` is no longer automatically installed when you create a fresh environment with `Python 3.12`, specifically if you are using `venv` (the standard library's virtual environment tool). To access` setuptools`, you must explicitly install it after …
> Bugfix/ python3.12 compatibility issue

- pyproject.toml
- test/cli/test_run.py
> py3.12 incompatibility with scipy and rdkit update

- .github/scripts/airtableops.py
- .github/workflows/tests_and_cleanup.yml
- ersilia/hub/content/base_information.py
- ersilia/utils/exceptions_utils/base_information_exceptions.py
- test/fields/test_airtable.py
- test/fields/test_base_information.py
This PR modifies the aitable interface and `BaseInformation` class to incorporate the new fields as below:
```yml
Environment Size # to dependency size
Image Size # model docker image size
Computational Performance 1 # computational performance for 1 input sample
Computational Performance 10 # computational performance for 10 input samples
Computational Performance 100 # computational performance for 100 input samples
```
Also to add adds unit tests for the `ReadmeMetadata`, `BaseInformation` classes and Mocked Airtable responses are used for tests.
- **`ReadmeMetadata`**: Tests the `write_information()` methods to ensure correct data retrieval and README generation.
- **`BaseInformation`**: Verifies that model attributes (title, description, performance metrics, etc.) are correctly set …
> Airtable field update and add unit testing

- ersilia/cli/commands/test.py
- ersilia/default.py
- ersilia/publish/inspect.py
- ersilia/publish/test.py
- ersilia/utils/spinner.py
> Refactoring Test Command 

- ersilia/serve/standard_api.py
Fix csv serialization if input result is neither a dict nor a single value
Closes #1541
> Resolve duplication of values in CSV serialization

- ersilia/serve/standard_api.py
Closes #1535 
PR modifies the `get_list_from_csv` method from the `StandardCSVRunApi` class to not skip rows with input values if such values have already been read in preceding rows.
> remove unnecessary input filtering

- ersilia/default.py
- ersilia/hub/fetch/actions/template_resolver.py
- ersilia/hub/fetch/fetch.py
- ersilia/hub/fetch/register/standard_example.py
- ersilia/utils/exceptions_utils/fetch_exceptions.py
Improved template resolver to use FastAPI as a prioritary option and deal with FastAPI versions.
**Status**
Done
Related to #1562
_Copilot generated text below_
This pull request introduces several changes to the `ersilia` package, focusing on enhancing FastAPI support, improving error handling, and adding new utility functions. Here are the most important changes:
* Added `FASTAPI_APPROVED_PYTHON_VERSIONS` to the list of approved Python versions in `ersilia/default.py`.
* Updated `is_fastapi` method in `ersilia/hub/fetch/actions/template_resolver.py` to include additional checks for …
> pre commit fixes

- ersilia/hub/content/base_information.py
This pull request updates the `publication` and `source_code` setter methods in `ersilia/hub/content/base_information.py` to handle `None`, `"none"`, and `"null"` values more gracefully by setting the respective attributes to `None`. This improves the robustness of the code when dealing with invalid or null-like input.
* `ersilia/hub/content/base_information.py` (`publication` method): Added checks to set `_publication` to `None` if `new_publication` is `None`, `"none"`, or `"null"`.
* `ersilia/hub/content/base_information.py` (`source_code` method): Added checks to set `_source_code` to `None` if `new_source_code` is `None`, `"none"`, or `"null"`.
> added exceptions for null publication and source code

- ersilia/hub/content/base_information.py
This pull request updates the `dockerhub` method in `ersilia/hub/content/base_information.py` to handle cases where the `new_dockerhub_url` is `None`, `"none"`, or `"null"` by setting the `_dockerhub` attribute to `None`.
Key change:
* Updated the `dockerhub` method to check if `new_dockerhub_url` is `None`, `"none"`, or `"null"`, and set the `_dockerhub` attribute to `None` in these cases. This ensures better handling of null-like values for the DockerHub URL.
> update base information with dockerhub

- ersilia/hub/content/base_information.py
This pull request adds validation to handle `None`, `"none"`, and `"null"` values consistently across several methods in the `ersilia/hub/content/base_information.py` file. The changes ensure that these values are interpreted as `None` for internal storage.
* `docker_architecture(self, new_docker_architecture)`: Added checks to set `_docker_architecture` to `None` if `new_docker_architecture` is `None`, `"none"`, or `"null"`.
* `s3(self, new_s3_url)`: Added logic to set `_s3` to `None` if `new_s3_url` is `None`, `"none"`, or `"null"`.
* `deployment(self, new_deployment)`: Updated to set `_deployment` to `None` if `new_deployment` is `None`, `"none"`, or `"null"`.
> docker architecture escaping and more

- ersilia/publish/test/services/runner.py
@GemmaTuron just for the record I updated the bash execution to be like this below to solve the issue:
```python
bash_script = f"""#!/usr/bin/env bash
set -euo pipefail
echo "Runner arch: $(uname -m)"
echo "Using conda prefix: {self._conda_prefix(self._is_base())}"
conda run -n {self.model_id} bash -c '
set -euo pipefail
echo "Inside conda env: $(python -V) - $(which python)"
cd "{os.path.dirname(run_sh_path)}"
echo "PWD inside conda run: $(pwd)"
ls -lah
bash ./run.sh . "{input_file_path}" "{bash_output_path}"
'
if [ ! -f "{bash_output_path}" ]; then
echo "ERROR: expected output file not found: {bash_output_path}" >&2
[ -f "{error_log_path}" ] && echo "==== STDERR ====" && cat …
```
> hotfix: using conda run for exectuing any conda related command
